spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:8870}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8083

bank-service:
  url: http://localhost:8084