spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:test@gmail.com}
    password: ${EMAIL_PASSWORD:test123}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

management:
  health:
    mail:
      enabled: false   # disable for local