server:
  port: 8084

spring:
  application:
    name: bank-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    com.fraud.bank: INFO