spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379

bank-service:
  url: http://localhost:8084

fraud-service:
  url: http://localhost:8082