package com.fraud.common.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * TransactionEvent — Shared Kafka Message DTO
 *
 * This POJO is serialized to JSON by the transaction-service (Kafka Producer)
 * and deserialized back by the fraud-detection-service (Kafka Consumer).
 *
 * Keeping it in common-dto ensures both services share an identical contract.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransactionEvent implements Serializable {

    /** Unique identifier for this transaction (UUID recommended) */
    private String transactionId;

    /**
     * ID of the user initiating the transaction.
     * For UPI payments this is the payer's email (set from JWT by the gateway).
     * For legacy transactions this is the manually provided userId.
     */
    private String userId;

    /**
     * Transaction amount in the smallest currency unit (e.g. paise / cents).
     * Using BigDecimal to avoid floating-point precision issues.
     */
    private BigDecimal amount;

    /** Physical or IP-based location of the transaction (e.g. "Mumbai", "192.168.1.1") */
    private String location;

    /** Device identifier or device type (e.g. "iPhone-12", "Android-Samsung-Galaxy") */
    private String device;

    /** Timestamp when the transaction was created — set by the transaction-service */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime timestamp;

    /**
     * Optional: merchant or payment category context.
     * Used by Spring AI for richer fraud analysis.
     */
    private String merchantCategory;

    // ─── UPI / NPCI Extension Fields ─────────────────────────────────────────
    // Populated only for UPI payments (POST /api/upi/pay).
    // Legacy transactions (POST /api/transactions) leave these null.

    /**
     * Payer's email — extracted from the JWT token by the API Gateway.
     * Same as userId for UPI payments.
     * DO NOT trust the request body for this field — gateway always overrides.
     */
    private String payerUserId;

    /**
     * Payee's UPI ID (e.g. "john@okaxis", "merchant@ybl").
     * Used by the payment processor to look up the payee's bank account.
     */
    private String payeeUpiId;

    /**
     * Payee's resolved userId/email.
     * Populated by the bank-service client during post-fraud payment processing.
     * Null until fraud-detection-service resolves it.
     */
    private String payeeUserId;

    /**
     * Payment mode: "BANK" (simulation via bank-service) or "RAZORPAY" (real payment).
     * Defaults to "BANK" if not specified.
     */
    private String paymentMode;

    /**
     * Distributed trace ID — generated by the API Gateway (UUID v4) and propagated
     * through all services via HTTP header (X-Trace-Id) and Kafka message body.
     * Included in every log line via MDC so a full transaction can be traced end-to-end
     * across API Gateway → Transaction Service → Kafka → Fraud Detection → Bank Service.
     */
    private String traceId;
}
